### ISSUE TITLE
User auth check

### ISSUE THREAD

**Issue by matthu24** [matthu24/bandwhich#1]

**Comment by s-pangburn** [comment]
- [x] Remove margin from `body`. This should fix the blank space around your nav bar
- [x] Get the nav bar much closer to what you would see on bandcamp's actual site.
- [x] "demo user" should be "demo login", just to be clearer to recruiters
- [x] The logo should be on the left, nav links on the far right
- [x] Logging in with blank fields leads me to a blank page. The console is full of errors.
  + Same with signup
- [x] Actually, whether I fill out the form or not, both forms lead me to a blank page every time. I don't think I can actually register an account
- [x] Demo login creates an infinite loop (and doesn't work)

**Comment by s-pangburn** [comment]
- [x] Errors should be red (possibly also centered)
- [x] Demo login should be underneath Login button (should be on both the login and signup pages)
- [x] Random urls like `/home` or `/something` should redirect to login
- [x] There should be a link on the login and signup forms to switch between them (`New User? Sign Up` and `Already a user? Log in`)

**Comment by s-pangburn** [comment]
- [x] "Log in" button should be `cursor: pointer` on hover
- [x] Errors should probably be centered with where you have them
- [x] "Hi username" and "logout" should probably be flipped
- [x] Login and Signup buttons should probably be the same width (that is, the width of the form)
- [ ] Try to have your "Don't have an account? Sign up" styled more like this (this is bandcamp's website)
![screen shot 2017-11-25 at 9 40 51 am](https://user-images.githubusercontent.com/8031316/33233021-c55bfbcc-d1c4-11e7-803c-b22f97d6a610.png)
  + No need for that fan, artist or label business, I just mean the CSS should look more like that. The current link looks a little thrown-in.
- [x] You shouldn't allow duplicate usernames
- [x] "Welcome to Bandwhich" looks a little out of place right now. Either find a way to integrate it with the image or don't have it there at all.

**Comment by s-pangburn** [comment]
Looks good! Awesome turnaround on this, Matt! I'll mark this feature as complete!

Eventually I still think you should restyle the "Or signup/login" text to be more like what I showed above, but for now this is more than good enough 👍
