### ISSUE TITLE
Check Artist Index/Show

### ISSUE THREAD

**Issue by matthu24** [matthu24/bandwhich#3]

**Comment by s-pangburn** [comment]
Some new issues with the user auth:

- [x] If you're already logged in and you visit the site, it takes you to the splash page, which has no links to take you to the index view. I'm essentially stuck unless I remember the index view url or I log out and back in.
- [x] Clicking the logo should take you to the front page or the artist view, depending on whether you're logged in or not.
- [x] That sandwich background on the login screen shouldn't be tiled. Also it should match the dimensions of your splash image.
- [x] The album images at the top of your artist index should be clickable links. Also, there should be just a little horizontal spacing between them, like on the bandcamp website.
- [x] The gray effect on hover for each artist index item should be just a little darker.
- [x] The artist page feels a little sparse. The album should probably have a description, just to flesh the page out more. Similarly, you should have a player somewhere on the page, the way bandcamp does on their website. 
- [x] "Lorem Ipsum is simply dummy text of the printing and typesetting industry...." <- This should be gibberish or it should be something that looks coherent with the website (i.e. something you came up with yourself) Copypasting this definition to every page looks out-of-place. Plus, it's not immediately clear what this text is supposed to be. An artist description? Label it as such if you're going to use gibberish text. Also the artist name should probably be under their avatar, again use the bandcamp site as a reference:
![screen shot 2017-11-28 at 11 04 27 am](https://user-images.githubusercontent.com/8031316/33338841-25df93c8-d42c-11e7-87d4-fccbda276828.png)
- [x] You don't need all these elements (particularly the ones about buying songs) but it should be pretty close. Pay attention to things like column width, organization of elements, etc.

**Comment by s-pangburn** [comment]
Also, if you don't think you're going to finish playlists in time, adding comments to each artist page like the ones you see below the album art in that screenshot would be another way to incorporate a CRUD cycle that might be more feasible. Let me know what you think!
